// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7iRObR_es33dNJf59n646gU47XLEYKPw',
    appId: '1:428624106878:web:0e1e4dc42fa8b4085b0f2f',
    messagingSenderId: '428624106878',
    projectId: 'ai-can-see-your-stroke',
    authDomain: 'ai-can-see-your-stroke.firebaseapp.com',
    storageBucket: 'ai-can-see-your-stroke.firebasestorage.app',
    measurementId: 'G-W1CNGX5L8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5Gt5ab5uJ0aWZEStL9-3LFwVpJCY2Q4',
    appId: '1:428624106878:android:9ea0a4d5a31370ff5b0f2f',
    messagingSenderId: '428624106878',
    projectId: 'ai-can-see-your-stroke',
    storageBucket: 'ai-can-see-your-stroke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDONTDUbcQiLMS2uUYENG7Qy4z9mQkyikA',
    appId: '1:428624106878:ios:df7f2dd027db36aa5b0f2f',
    messagingSenderId: '428624106878',
    projectId: 'ai-can-see-your-stroke',
    storageBucket: 'ai-can-see-your-stroke.firebasestorage.app',
    iosBundleId: 'com.example.sicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDONTDUbcQiLMS2uUYENG7Qy4z9mQkyikA',
    appId: '1:428624106878:ios:df7f2dd027db36aa5b0f2f',
    messagingSenderId: '428624106878',
    projectId: 'ai-can-see-your-stroke',
    storageBucket: 'ai-can-see-your-stroke.firebasestorage.app',
    iosBundleId: 'com.example.sicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7iRObR_es33dNJf59n646gU47XLEYKPw',
    appId: '1:428624106878:web:e45e6e46996161715b0f2f',
    messagingSenderId: '428624106878',
    projectId: 'ai-can-see-your-stroke',
    authDomain: 'ai-can-see-your-stroke.firebaseapp.com',
    storageBucket: 'ai-can-see-your-stroke.firebasestorage.app',
    measurementId: 'G-HHRW6K7R2M',
  );
}
